apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-two-deploy
  namespace: apidoc-aggregator
  labels:
    app: microservice-two
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-two
  template:
    metadata:
      labels:
        app: microservice-two
    spec:
      containers:
      - name: microservice-two
        image: feet312/microservice-two  # on server
        # image: microservice-two       # local
        ports: 
        - name: http
          containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: microservice-two-service
  namespace: apidoc-aggregator
spec:
  # type: NodePort
  selector:
    app: microservice-two
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      # nodePort: 32180
---
